---
name: Build Java PR

# yamllint disable rule:comments
# yamllint disable-line rule:truthy
on: pull_request
# yamllint enable rule:comments

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/maven_java_callable.yml@d55afdff37918b3f42bc21607b741113f5e3fd4f # 1.26.29
    secrets: inherit
