---
name: Build Java PR

# yamllint disable-line rule:truthy
on: pull_request

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/maven_java_callable.yml@7ca369a7b39026826ce13e86443b1bee7766f4f4 # 1.22.54
    secrets: inherit
