---
name: Build Java PR

# yamllint disable-line rule:truthy
on: pull_request

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/maven_java_callable.yml@590c56856a43c909afcc719f44ca96e3c2569b17 # 1.22.53
    secrets: inherit
