---
name: Build Java PR

# yamllint disable rule:comments
# yamllint disable-line rule:truthy
on: pull_request
# yamllint enable rule:comments

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/maven_java_callable.yml@dc2e66ba9e8fbfa2d8494cbc6d6eed01f947d42a # 1.26.12
    secrets: inherit
